[template]
src = "alertmanager.yml.tmpl"
dest = "/etc/prometheus/alertmanager.yml"
prefix = "/%%PROJECT%%/%%ARENA%%"

uid = 0
gid = 0
mode = "0640"

keys = [
    "/config/*",
    "/config"
]

reload_cmd = "/bin/systemctl reload-or-restart alertmanager"
