[template]
src = "prometheus-custom-rules.prom.tmpl"
dest = "/etc/prometheus/rules.d/custom-rules.prom"
prefix = "/monitoring/%%ARENA%%"

uid = 0
gid = 0
mode = "0640"

keys = [
    "/"
]

reload_cmd = "/bin/systemctl restart prometheus"
