#!/bin/bash

if nubis-metadata NUBIS_ARENA > /dev/null 2>&1; then
    NUBIS_ARENA=$(nubis-metadata NUBIS_ARENA)
fi
echo "Enabling node_exporter in '${NUBIS_ARENA:-Arena_Not_Set}'"

consulate kv set "arenas/$NUBIS_ARENA/global/node_exporter/config/enabled" 1

if nubis-metadata NUBIS_PROJECT > /dev/null 2>&1; then
    NUBIS_PROJECT=$(nubis-metadata NUBIS_PROJECT)
fi
KV_PREFIX="$NUBIS_PROJECT/$NUBIS_ARENA/config"

if nubis-metadata INSTANCE_IDENTITY_REGION > /dev/null 2>&1; then
    NUBIS_REGION=$(nubis-metadata INSTANCE_IDENTITY_REGION)
    consulate kv set "$KV_PREFIX/RegionName" "$NUBIS_REGION"
fi

if nubis-metadata NUBIS_ARENA_INDEX > /dev/null 2>&1; then
    NUBIS_ARENA_INDEX=$(nubis-metadata NUBIS_ARENA_INDEX)
    consulate kv set "$KV_PREFIX/ArenaIndex" "$NUBIS_ARENA_INDEX"
else
    consulate kv rm "$KV_PREFIX/ArenaIndex"
fi

if nubis-metadata NUBIS_PROMETHEUS_SLACK_URL > /dev/null 2>&1; then
    NUBIS_PROMETHEUS_SLACK_URL=$(nubis-metadata NUBIS_PROMETHEUS_SLACK_URL)
    consulate kv set "$KV_PREFIX/Slack/Url" "$NUBIS_PROMETHEUS_SLACK_URL"
else
    consulate kv rm "$KV_PREFIX/Slack/Url"
fi

if nubis-metadata NUBIS_PROMETHEUS_SLACK_CHANNEL > /dev/null 2>&1; then
    NUBIS_PROMETHEUS_SLACK_CHANNEL=$(nubis-metadata NUBIS_PROMETHEUS_SLACK_CHANNEL)
    consulate kv set "$KV_PREFIX/Slack/Channel" "$NUBIS_PROMETHEUS_SLACK_CHANNEL"
else
    consulate kv rm "$KV_PREFIX/Slack/Channel"
fi

if nubis-metadata NUBIS_PROMETHEUS_NOTIFICATION_EMAIL > /dev/null 2>&1; then
    NUBIS_PROMETHEUS_NOTIFICATION_EMAIL=$(nubis-metadata NUBIS_PROMETHEUS_NOTIFICATION_EMAIL)
    consulate kv set "$KV_PREFIX/Email/Destination" "$NUBIS_PROMETHEUS_NOTIFICATION_EMAIL"
else
    consulate kv rm "$KV_PREFIX/Email/Destination"
fi

if nubis-metadata NUBIS_ACCOUNT > /dev/null 2>&1; then
    NUBIS_ACCOUNT=$(nubis-metadata NUBIS_ACCOUNT)
    consulate kv set "$KV_PREFIX/AccountName" "$NUBIS_ACCOUNT"
else
    consulate kv rm "$KV_PREFIX/AccountName"
fi

if nubis-metadata NUBIS_TECHNICAL_CONTACT > /dev/null 2>&1; then
    NUBIS_TECHNICAL_CONTACT=$(nubis-metadata NUBIS_TECHNICAL_CONTACT)
    consulate kv set "$KV_PREFIX/TechnicalContact" "$NUBIS_TECHNICAL_CONTACT"
else
    consulate kv rm "$KV_PREFIX/TechnicalContact"
fi

if nubis-metadata INSTANCE_IDENTITY_ACCOUNTID > /dev/null 2>&1; then
    NUBIS_ACCOUNT_ID=$(nubis-metadata INSTANCE_IDENTITY_ACCOUNTID)
    consulate kv set "$KV_PREFIX/AccountID" "$NUBIS_ACCOUNT_ID"
else
    consulate kv rm "$KV_PREFIX/AccountID"
fi

if [ "${NUBIS_ARENA}" != "" ]; then
    consulate kv set "$KV_PREFIX/Arena" "$NUBIS_ARENA"
else
    consulate kv rm "$KV_PREFIX/Arena"
fi

if nubis-metadata NUBIS_PROMETHEUS_PLATFORM_CRITICAL_PAGERDUTY_SERVICE_KEY > /dev/null 2>&1; then
    NUBIS_PROMETHEUS_PLATFORM_CRITICAL_PAGERDUTY_SERVICE_KEY=$(nubis-metadata NUBIS_PROMETHEUS_PLATFORM_CRITICAL_PAGERDUTY_SERVICE_KEY)
    consulate kv set "$KV_PREFIX/PagerDuty/PlatformCriticalServiceKey" "$NUBIS_PROMETHEUS_PLATFORM_CRITICAL_PAGERDUTY_SERVICE_KEY"
else
    consulate kv rm "$KV_PREFIX/PagerDuty/PlatformCriticalServiceKey"
fi

if nubis-metadata NUBIS_PROMETHEUS_PLATFORM_NON_CRITICAL_PAGERDUTY_SERVICE_KEY > /dev/null 2>&1; then
    NUBIS_PROMETHEUS_PLATFORM_NON_CRITICAL_PAGERDUTY_SERVICE_KEY=$(nubis-metadata NUBIS_PROMETHEUS_PLATFORM_NON_CRITICAL_PAGERDUTY_SERVICE_KEY)
    consulate kv set "$KV_PREFIX/PagerDuty/PlatformNonCriticalServiceKey" "$NUBIS_PROMETHEUS_PLATFORM_NON_CRITICAL_PAGERDUTY_SERVICE_KEY"
else
    consulate kv rm "$KV_PREFIX/PagerDuty/PlatformNonCriticalServiceKey"
fi

if nubis-metadata NUBIS_PROMETHEUS_APP_CRITICAL_PAGERDUTY_SERVICE_KEY > /dev/null 2>&1; then
    NUBIS_PROMETHEUS_APP_CRITICAL_PAGERDUTY_SERVICE_KEY=$(nubis-metadata NUBIS_PROMETHEUS_APP_CRITICAL_PAGERDUTY_SERVICE_KEY)
    consulate kv set "$KV_PREFIX/PagerDuty/ApplicationCriticalServiceKey" "$NUBIS_PROMETHEUS_APP_CRITICAL_PAGERDUTY_SERVICE_KEY"
else
    consulate kv rm "$KV_PREFIX/PagerDuty/ApplicationCriticalServiceKey"
fi

if nubis-metadata NUBIS_PROMETHEUS_APP_NON_CRITICAL_PAGERDUTY_SERVICE_KEY > /dev/null 2>&1; then
    NUBIS_PROMETHEUS_APP_NON_CRITICAL_PAGERDUTY_SERVICE_KEY=$(nubis-metadata NUBIS_PROMETHEUS_APP_NON_CRITICAL_PAGERDUTY_SERVICE_KEY)
    consulate kv set "$KV_PREFIX/PagerDuty/ApplicationNonCriticalServiceKey" "$NUBIS_PROMETHEUS_APP_NON_CRITICAL_PAGERDUTY_SERVICE_KEY"
else
    consulate kv rm "$KV_PREFIX/PagerDuty/ApplicationNonCriticalServiceKey"
fi

if nubis-metadata NUBIS_PROMETHEUS_LIVE_APP > /dev/null 2>&1; then
    NUBIS_PROMETHEUS_LIVE_APP=$(nubis-metadata NUBIS_PROMETHEUS_LIVE_APP)
    consulate kv set "$KV_PREFIX/LiveApp" "$NUBIS_PROMETHEUS_LIVE_APP"
else
    consulate kv rm "$KV_PREFIX/LiveApp"
fi

if nubis-metadata NUBIS_ACCOUNT > /dev/null 2>&1; then
    NUBIS_ACCOUNT=$(nubis-metadata NUBIS_ACCOUNT)
fi
if nubis-metadata NUBIS_DOMAIN > /dev/null 2>&1; then
    NUBIS_DOMAIN=$(nubis-metadata NUBIS_DOMAIN)
fi
NUBIS_MON_DOMAIN="mon.$NUBIS_ARENA.$NUBIS_REGION.$NUBIS_ACCOUNT.$NUBIS_DOMAIN"
consulate kv set "$KV_PREFIX/MonDomain" "$NUBIS_MON_DOMAIN"
consulate kv set "$KV_PREFIX/Domain" "$NUBIS_DOMAIN"

SECRET_FEDERATION_PASSWORD=$(nubis-secret get federation/password)
FEDERATION_PASSWORD=$(consulate kv get "$KV_PREFIX/Federation/Password")
if [ "$FEDERATION_PASSWORD" != "$SECRET_FEDERATION_PASSWORD" ]; then

  FEDERATION_HTPASSWORD=$(htpasswd -nb federation "$SECRET_FEDERATION_PASSWORD")

  consulate kv set "$KV_PREFIX/Federation/Password" "$SECRET_FEDERATION_PASSWORD"
  consulate kv set "$KV_PREFIX/Federation/HTPassword" "$FEDERATION_HTPASSWORD"
fi

SECRET_ADMIN_PASSWORD=$(nubis-secret get admin/password)
ADMIN_PASSWORD=$(consulate kv get "$KV_PREFIX/admin/Password")
if [ "$ADMIN_PASSWORD" != "$SECRET_ADMIN_PASSWORD" ]; then

  ADMIN_HTPASSWORD=$(htpasswd -nb admin "$SECRET_ADMIN_PASSWORD")

  consulate kv set "$KV_PREFIX/Admin/Password" "$SECRET_ADMIN_PASSWORD"
  consulate kv set "$KV_PREFIX/Admin/HTPassword" "$ADMIN_HTPASSWORD"
fi
