forge "https://forgeapi.puppetlabs.com"

mod 'spantree/upstart','0.0.3'

mod 'bfraser/grafana',
    :git => 'https://github.com/bfraser/puppet-grafana.git',
    :ref => '6d426d5ccc52ff23dbbcfc45290dafd224b5d2bc'

mod 'puppetlabs/java', '1.6.0'
