#!/bin/bash

EFS_ID=$(nubis-metadata NUBIS_PROMETHEUS_FSID)
if [ "$EFS_ID" != "" ]; then
  NUBIS_REGION=$(nubis-region)
  EFS_TARGET="$EFS_ID.efs.$NUBIS_REGION.amazonaws.com"
  echo "Mounting EFS:$EFS_ID"
  mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 "$EFS_TARGET:/" "/var/lib/prometheus"
fi
