#!/bin/bash

NUBIS_ENVIRONMENT=$(nubis-metadata NUBIS_ENVIRONMENT)

echo "Enabling node_exporter"

consulate kv set "environments/$NUBIS_ENVIRONMENT/global/node_exporter/config/enabled" 1

NUBIS_PROJECT=$(nubis-metadata NUBIS_PROJECT)

KV_PREFIX="$NUBIS_PROJECT/$NUBIS_ENVIRONMENT/config"

NUBIS_REGION=$(nubis-region)
if [ "$NUBIS_REGION" != "" ]; then
  consulate kv set "$KV_PREFIX/RegionName" "$NUBIS_REGION"
fi

NUBIS_PROMETHEUS_SLACK_URL=$(nubis-metadata NUBIS_PROMETHEUS_SLACK_URL)
if [ "$NUBIS_PROMETHEUS_SLACK_URL" != "" ]; then
  consulate kv set "$KV_PREFIX/Slack/Url" "$NUBIS_PROMETHEUS_SLACK_URL"
else
  consulate kv rm "$KV_PREFIX/Slack/Url"
fi

NUBIS_PROMETHEUS_SLACK_CHANNEL=$(nubis-metadata NUBIS_PROMETHEUS_SLACK_CHANNEL)
if [ "$NUBIS_PROMETHEUS_SLACK_URL" != "" ]; then
  consulate kv set "$KV_PREFIX/Slack/Channel" "$NUBIS_PROMETHEUS_SLACK_CHANNEL"
else
  consulate kv rm "$KV_PREFIX/Slack/Channel"
fi

NUBIS_PROMETHEUS_SINK_SLACK_URL=$(nubis-metadata NUBIS_PROMETHEUS_SINK_SLACK_URL)
if [ "$NUBIS_PROMETHEUS_SINK_SLACK_URL" != "" ]; then
  consulate kv set "$KV_PREFIX/Sink/Slack/Url" "$NUBIS_PROMETHEUS_SINK_SLACK_URL"
else
  consulate kv rm "$KV_PREFIX/Sink/Slack/Url"
fi

NUBIS_PROMETHEUS_SINK_SLACK_CHANNEL=$(nubis-metadata NUBIS_PROMETHEUS_SINK_SLACK_CHANNEL)
if [ "$NUBIS_PROMETHEUS_SINK_SLACK_URL" != "" ]; then
  consulate kv set "$KV_PREFIX/Sink/Slack/Channel" "$NUBIS_PROMETHEUS_SINK_SLACK_CHANNEL"
else
  consulate kv rm "$KV_PREFIX/Sink/Slack/Channel"
fi

NUBIS_PROMETHEUS_NOTIFICATION_EMAIL=$(nubis-metadata NUBIS_PROMETHEUS_NOTIFICATION_EMAIL)
if [ "$NUBIS_PROMETHEUS_NOTIFICATION_EMAIL" != "" ]; then
  consulate kv set "$KV_PREFIX/Email/Destination" "$NUBIS_PROMETHEUS_NOTIFICATION_EMAIL"
else
  consulate kv rm "$KV_PREFIX/Email/Destination"
fi

NUBIS_PROMETHEUS_SINK_NOTIFICATION_EMAIL=$(nubis-metadata NUBIS_PROMETHEUS_SINK_NOTIFICATION_EMAIL)
if [ "$NUBIS_PROMETHEUS_SINK_NOTIFICATION_EMAIL" != "" ]; then
  consulate kv set "$KV_PREFIX/Sink/Email/Destination" "$NUBIS_PROMETHEUS_SINK_NOTIFICATION_EMAIL"
else
  consulate kv rm "$KV_PREFIX/Sink/Email/Destination"
fi

NUBIS_ACCOUNT=$(nubis-metadata NUBIS_ACCOUNT)
if [ "$NUBIS_ACCOUNT" != "" ]; then
  consulate kv set "$KV_PREFIX/AccountName" "$NUBIS_ACCOUNT"
else
  consulate kv rm "$KV_PREFIX/AccountName"
fi

NUBIS_TECHNICAL_CONTACT=$(nubis-metadata NUBIS_TECHNICAL_CONTACT)
if [ "$NUBIS_TECHNICAL_CONTACT" != "" ]; then
  consulate kv set "$KV_PREFIX/TechnicalContact" "$NUBIS_TECHNICAL_CONTACT"
else
  consulate kv rm "$KV_PREFIX/TechnicalContact"
fi

NUBIS_ACCOUNT_ID=$(curl --retry 5 -fqs http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .accountId)
if [ "$NUBIS_ACCOUNT_ID" != "" ]; then
  consulate kv set "$KV_PREFIX/AccountID" "$NUBIS_ACCOUNT_ID"
else
  consulate kv rm "$KV_PREFIX/AccountID"
fi

if [ "$NUBIS_ENVIRONMENT" != "" ]; then
  consulate kv set "$KV_PREFIX/EnvironmentName" "$NUBIS_ENVIRONMENT"
else
  consulate kv rm "$KV_PREFIX/EnvironmentName"
fi

NUBIS_PROMETHEUS_PAGERDUTY_SERVICE_KEY=$(nubis-metadata NUBIS_PROMETHEUS_PAGERDUTY_SERVICE_KEY)
if [ "$NUBIS_PROMETHEUS_PAGERDUTY_SERVICE_KEY" != "" ]; then
  consulate kv set "$KV_PREFIX/PagerDuty/ServiceKey" "$NUBIS_PROMETHEUS_PAGERDUTY_SERVICE_KEY"
else
  consulate kv rm "$KV_PREFIX/PagerDuty/ServiceKey"
fi

NUBIS_PROMETHEUS_SINK_PAGERDUTY_SERVICE_KEY=$(nubis-metadata NUBIS_PROMETHEUS_SINK_PAGERDUTY_SERVICE_KEY)
if [ "$NUBIS_PROMETHEUS_SINK_PAGERDUTY_SERVICE_KEY" != "" ]; then
  consulate kv set "$KV_PREFIX/Sink/PagerDuty/ServiceKey" "$NUBIS_PROMETHEUS_SINK_PAGERDUTY_SERVICE_KEY"
else
  consulate kv rm "$KV_PREFIX/Sink/PagerDuty/ServiceKey"
fi

NUBIS_PROMETHEUS_LIVE_APP=$(nubis-metadata NUBIS_PROMETHEUS_LIVE_APP)
if [ "$NUBIS_PROMETHEUS_LIVE_APP" != "" ]; then
  consulate kv set "$KV_PREFIX/LiveApp" "$NUBIS_PROMETHEUS_LIVE_APP"
else
  consulate kv rm "$KV_PREFIX/LiveApp"
fi

NUBIS_MON_DOMAIN="mon.$NUBIS_ENVIRONMENT.$NUBIS_REGION.$(nubis-metadata NUBIS_ACCOUNT).$(nubis-metadata NUBIS_DOMAIN)"
consulate kv set "$KV_PREFIX/MonDomain" "$NUBIS_MON_DOMAIN"

SECRET_FEDERATION_PASSWORD=$(nubis-secret get federation/password)
FEDERATION_PASSWORD=$(consulate kv get "$KV_PREFIX/Federation/Password")
if [ "$FEDERATION_PASSWORD" != "$SECRET_FEDERATION_PASSWORD" ]; then

  FEDERATION_HTPASSWORD=$(htpasswd -nb federation "$SECRET_FEDERATION_PASSWORD")

  consulate kv set "$KV_PREFIX/Federation/Password" "$SECRET_FEDERATION_PASSWORD"
  consulate kv set "$KV_PREFIX/Federation/HTPassword" "$FEDERATION_HTPASSWORD"
fi

SECRET_ADMIN_PASSWORD=$(nubis-secret get admin/password)
ADMIN_PASSWORD=$(consulate kv get "$KV_PREFIX/admin/Password")
if [ "$ADMIN_PASSWORD" != "$SECRET_ADMIN_PASSWORD" ]; then

  ADMIN_HTPASSWORD=$(htpasswd -nb admin "$SECRET_ADMIN_PASSWORD")

  consulate kv set "$KV_PREFIX/Admin/Password" "$SECRET_ADMIN_PASSWORD"
  consulate kv set "$KV_PREFIX/Admin/HTPassword" "$ADMIN_HTPASSWORD"
fi
